In [4]:
import torch


# Just the functions in the torch

In [5]:
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([-47, -73, -77, -35, -55,  57])


In [6]:
tensor = torch.tensor([[0.1, 1.2],[2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
input = torch.empty(2,3)
input 

tensor([[-7.5094e-09,  1.0706e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3,10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
logspace = torch.logspace(start = -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

# Actual Program

In [23]:
import torch
import numpy as np
import time 

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


# Using this library to record execution time %%time is to record the time taken for the cell to execute 


In [33]:
%%time 
start_time = time.time()

# Matrix operations starts here on
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .4f}")

 0.0000
CPU times: total: 0 ns
Wall time: 0 ns


In [31]:
# This cell shows the difference between the time taken by gpu and cpu for the execution 

torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")



start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.02500820
 0.11478424


In [34]:
# Define a probability tensor
# These may helpful to us in the future for prediction of what word is coming next

probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1])


In [35]:
# Used for concatination
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [36]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [37]:
# Here everything in the matrix exponentiate (-inf) mean negative infinity
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [38]:
torch.exp(out) # Exponent values for the previous matrix

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [40]:
# Transpose is like the swapping the places of the elements in the matrix
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [42]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3]) # Stack helps to placce all the batches in order 
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([ 4.0535,  6.0291, -3.3296], grad_fn=<SqueezeBackward4>)


In [46]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# Apply the softmax function

softmax_output = F.softmax(tensor1, dim = 0)

softmax_output

tensor([0.0900, 0.2447, 0.6652])